version: '3.6'
services:
  backend:
    build:
      context: .
      target: backend
    restart: unless-stopped
    tty: true
    working_dir: /home/node/app
    ports:
      - '11000:11000'
    volumes:
      - '.:/home/node/app'
      - /home/node/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true npm run start:dev
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root

    ports:
      - '5432:5432'
    volumes:
      - ./docker/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
